use scholarSearchDB;

INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Michael', 'Wolfe', 'terry08@tran.com', 'stephaniepeterson', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('James', 'Hill', 'andersenjason@yahoo.com', 'tgordon', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Jason', 'Morrow', 'imcdaniel@ruiz-weaver.com', 'amy33', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Kelsey', 'Hernandez', 'jacquelineking@beasley-hardin.net', 'garzarobert', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Nichole', 'Richards', 'parkernancy@gmail.com', 'kristinkerr', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Evan', 'Yang', 'brandonblackburn@bender-york.com', 'sjohnson', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Jennifer', 'Lowery', 'melissa48@lane-wilson.org', 'stevenbrennan', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Geoffrey', 'Moore', 'karen56@gmail.com', 'eringreer', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Bryan', 'Smith', 'cartercarlos@gmail.com', 'wesley41', 'pass');
INSERT INTO Companies (name, lastName, email, username, password) VALUES ('Christopher', 'Carrillo', 'wayne99@smith-henry.com', 'crystal07', 'pass');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Marcus', 'Osborn', 'melaniebishop@hunter-harris.com', 'jacksoneric', 'pass', 'approved');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Jerry', 'Scott', 'william38@hotmail.com', 'zglass', 'pass', 'denied');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Matthew', 'Jones', 'meagangordon@hotmail.com', 'mcconnellrobin', 'pass', 'none');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Brenda', 'Collins', 'sethzimmerman@yahoo.com', 'beth92', 'pass', 'none');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Sarah', 'Hill', 'xbaker@hotmail.com', 'ahale', 'pass', 'requested');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Tonya', 'Davis', 'austinorozco@shaw-smith.info', 'moracourtney', 'pass', 'none');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Victoria', 'Guerrero', 'jamescarl@clark.com', 'bmckay', 'pass', 'denied');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Daniel', 'Perez', 'rebeccagolden@moore.com', 'coxjerry', 'pass', 'approved');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Brandon', 'Davis', 'kylie11@hotmail.com', 'reeddavid', 'pass', 'approved');
INSERT INTO Students (name, lastName, email, username, password, company_request_status) VALUES ('Larry', 'Gonzales', 'yvonnefisher@jones-jones.biz', 'justinleblanc', 'pass', 'none');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Automated background utilization', 'Keep activity glass customer time certain. Tv against plant check interview authority.', 2934, '2025-10-10', 7, 'pending');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Synergized mission-critical initiative', 'Make create course player.', 4919, '2026-01-10', 4, 'pending');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Customer-focused asymmetric protocol', 'Us important together.', 2875, '2025-07-12', 8, 'pending');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Monitored eco-centric core', 'Her nothing listen everything. Effect capital bag choice.', 1218, '2025-12-14', 5, 'pending');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Distributed global data-warehouse', 'Television feel music street culture common. Artist live affect federal history memory certain.', 4604, '2025-10-19', 3, 'pending');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Right-sized analyzing interface', 'Power why then hold responsibility sell develop chair. Serious city he recent usually social.', 1335, '2025-07-15', 8, 'approved');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Diverse actuating complexity', 'Budget sort plan. Recent effect laugh list painting. Idea writer good plant weight.', 3032, '2026-01-09', 6, 'approved');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Switchable static flexibility', 'Day station assume our hand.', 3980, '2026-01-25', 2, 'approved');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Intuitive multimedia firmware', 'Which fly art approach medical point. Debate could talk difficult choice among.', 3313, '2025-12-22', 10, 'approved');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('User-centric 6thgeneration neural-net', 'Left race attack away other important.', 2238, '2025-12-16', 7, 'approved');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Cross-group zero-defect leverage', 'Tell we now training base investment tell.', 4098, '2026-01-19', 9, 'denied');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Optional multi-tasking budgetary management', 'Summer morning energy attention exactly. Rule beyond decision power win center around.', 3708, '2025-06-22', 2, 'denied');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Automated secondary firmware', 'Enough product create address heart collection because. Water support institution up decide forget.', 4329, '2025-10-18', 7, 'denied');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Synergized static budgetary management', 'Number either once old. Baby rock goal.', 4396, '2025-09-08', 3, 'denied');
INSERT INTO Scholarships (title, description, amount, deadline, company_id, status) VALUES ('Advanced bifurcated solution', 'Born in wish light likely. Practice window turn degree. Three small cause into enter.', 3451, '2026-02-19', 1, 'denied');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (8, 15, 'pending');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (5, 9, 'pending');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (1, 1, 'pending');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (4, 15, 'pending');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (3, 6, 'pending');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (6, 4, 'accepted');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (10, 6, 'accepted');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (5, 10, 'accepted');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (1, 15, 'accepted');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (4, 14, 'accepted');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (1, 9, 'rejected');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (4, 13, 'rejected');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (7, 11, 'rejected');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (2, 5, 'rejected');
INSERT INTO Applications (student_id, scholarship_id, application_status) VALUES (7, 3, 'rejected');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (15, '', 'pending');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (6, '', 'pending');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (3, '', 'pending');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (2, '', 'pending');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (11, '', 'pending');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (11, '', 'reviewed');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (9, '', 'reviewed');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (6, '', 'reviewed');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (11, '', 'reviewed');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (12, '', 'reviewed');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (5, '', 'resolved');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (8, '', 'resolved');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (1, '', 'resolved');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (14, '', 'resolved');
INSERT INTO Reports (scholarship_id, reason, status) VALUES (12, '', 'resolved');
INSERT INTO SavedScholarships (application_id, student_id) VALUES (8, 4);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (3, 3);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (12, 7);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (9, 7);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (12, 8);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (4, 9);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (13, 5);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (10, 8);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (6, 8);
INSERT INTO SavedScholarships (application_id, student_id) VALUES (14, 10);